name: Deploy to Supabase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        
      - name: Install Supabase CLI
        run: npm install -g supabase
        
      - name: Login to Supabase
        run: supabase login --non-interactive --token ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        
      - name: Deploy to Supabase
        run: supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        
      - name: Verify Deployment
        run: echo "Deployment completed successfully" 